name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: 1.17.8
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.0.2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 15.11.x

      - name: Building static assets
        run: (cd client && yarn install --immutable && yarn build)

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: go test -race -coverprofile=./c.out -covermode=atomic -v ./...

      - name: Report code coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=./c.out -service=github
